# docker-compose.yml
version: '3.8'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: ${PHP_CONTAINER_NAME}
        working_dir: /usr/share/nginx/html
        volumes:
            - ${APP_PATH}:/usr/share/nginx/html
        depends_on:
            - db

    nginx:
        image: nginx:stable-alpine
        container_name: ${NGINX_CONTAINER_NAME}
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ${APP_PATH}:/usr/share/nginx/html:ro
            - ./vhost.prod.conf:/etc/nginx/conf.d/default.conf:ro
            - ../certs/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
            - ../certs/privkey.pem:/etc/nginx/certs/privkey.pem:ro
        depends_on:
            - php

    db:
        image: ${DB_IMAGE}
        container_name: ${DB_CONTAINER_NAME}
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
            MYSQL_DATABASE:      ${MYSQL_DATABASE}
            MYSQL_USER:          ${MYSQL_USER}
            MYSQL_PASSWORD:      ${MYSQL_PASSWORD}
        volumes:
            - ${DB_PATH}:/var/lib/mysql
