version: '3.8'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: ${PHP_CONTAINER_NAME}
        working_dir: /usr/share/nginx/html
        volumes:
            - ${APP_PATH}:/usr/share/nginx/html
        depends_on:
            - db
        networks:
            webnet:
                aliases:
                    - ineasy_php

    nginx:
        image: nginx:stable-alpine
        container_name: ${NGINX_CONTAINER_NAME}
        volumes:
            - ${APP_PATH}:/usr/share/nginx/html:ro
        depends_on:
            - php
        networks:
            webnet:
                aliases:
                    - ineasy_nginx

    db:
        image: ${DB_IMAGE}
        container_name: ${DB_CONTAINER_NAME}
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ${DB_PATH}:/var/lib/mysql
        networks:
            - webnet

networks:
    webnet:
        driver: bridge
