# docker-compose.yml
version: '3.8'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app_php
        working_dir: /var/www/html
        volumes:
            - ../APP/:/var/www/html:cached
        depends_on:
            - db

    nginx:
        image: nginx:1.25
        container_name: app_nginx
        ports:
            - "80:80"
        volumes:
            - ../APP/:/var/www/html:cached
            - ./vhost.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - php

    db:
        image: mysql:8.0
        container_name: app_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
